name: Build and test Logfile::Tail

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '12 5 2,16 * *'

jobs:
  build:
    name: Run tests in container
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'registry.fedoraproject.org/fedora:latest'
          - 'quay.io/centos/centos:stream9'
          - 'quay.io/centos/centos:stream8'
          - 'registry.centos.org/centos:7'
    steps:
      - uses: actions/checkout@v2
      - name: Set the right OS in the Dockerfile
        run: sed "s#^FROM.*#FROM ${{ matrix.os }}#" ci/Dockerfile
      - name: Build image
        run: docker build -t logfile-tail -f ci/Dockerfile .
      - name: Run the tests with installed module
        run: docker run -e LOGFILE_TAIL_SCRIPT=/usr/bin/logfile-tail --rm logfile-tail t/test.sh
  native:
    name: Run tests on native Ubuntus
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: perl Makefile.PL
      - run: make
      - run: sudo make install
      - name: Run the tests with installed module
        run: LOGFILE_TAIL_SCRIPT=/usr/local/bin/logfile-tail make test
  readme:
    name: Check the README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y perl-doc libpod-markdown-perl
      - run: perl Makefile.PL
      - run: mv README.md README.md.orig
      - run: make README.md
      - run: diff -u README.md.orig README.md
